export const userTypes = {
  SET_AUTHENTICATED: "SET_AUTHENTICATED",
  SET_UNAUTHENTICATED: "SET_UNAUTHENTICATED",
  SET_USER: "SET_USER",
  LOADING: "LOADING_USER"
};

export const uiTypes = {
  SET_ERRORS: "SET_ERRORS",
  LOADING: "LOADING_UI",
  CLEAR_ERRORS: "CLEAR_ERRORS"
};

export const dataTypes = {
  SET_POSTS: "SET_POSTS",
  SET_POST: "SET_POST",
  LOADING: "LOADING_DATA",
  APPROVE_POST: "APPROVE_POST",
  DISAPPROVE_POST: "DISAPPROVE_POST",
  DELETE_POST: "DELETE_POST",
  ADD_POST: "ADD_POST"
};
